In [ ]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Verileri scale etmek
255 RGB'de max sayı olduğundan ona bölerek scale edebiliriz

In [14]:
X_train_scaled = X_train/255
X_test_scaled = X_test/255

print(X_train_scaled)
print(X_test_scaled)

[[[[0.34117647 0.34117647 0.33333333]
   [0.34117647 0.34117647 0.33333333]
   [0.36470588 0.36470588 0.35686275]
   ...
   [0.54901961 0.55294118 0.56078431]
   [0.58823529 0.59215686 0.6       ]
   [0.53333333 0.5372549  0.54509804]]

  [[0.35294118 0.35294118 0.34509804]
   [0.36078431 0.36078431 0.35294118]
   [0.3254902  0.3254902  0.31764706]
   ...
   [0.52941176 0.53333333 0.54117647]
   [0.56470588 0.56862745 0.57647059]
   [0.51372549 0.51764706 0.5254902 ]]

  [[0.30196078 0.30196078 0.29411765]
   [0.3372549  0.3372549  0.32941176]
   [0.34117647 0.34117647 0.33333333]
   ...
   [0.54901961 0.55294118 0.56078431]
   [0.59607843 0.6        0.60784314]
   [0.54509804 0.54901961 0.55686275]]

  ...

  [[0.49411765 0.49803922 0.50588235]
   [0.59215686 0.59607843 0.60392157]
   [0.58431373 0.58823529 0.59607843]
   ...
   [0.48627451 0.49019608 0.50588235]
   [0.56078431 0.56470588 0.58039216]
   [0.44705882 0.45098039 0.46666667]]

  [[0.54117647 0.54509804 0.55294118]
   [0.6

# Modelin Eğitilmesi

Tensorflow/Keras kütüphanelerinin yüklenmesi

In [16]:
import tensorflow as tf
import tensorflow_hub as hub

In [17]:
# mobilenet modeli kullanıldı

mobilenet = 'https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4'

pretrained_model = hub.KerasLayer(mobilenet, input_shape=(224, 224, 3), trainable=False)

In [18]:
num_of_classes = 2 # cat & dog

model = tf.keras.Sequential([
    pretrained_model, 
    tf.keras.layers.Dense(num_of_classes) # output layer 
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 1280)              2257984   
                                                                 
 dense (Dense)               (None, 2)                 2562      
                                                                 
Total params: 2,260,546
Trainable params: 2,562
Non-trainable params: 2,257,984
_________________________________________________________________


In [19]:
model.compile(
    optimizer = 'adam', 
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ['acc']
)

In [20]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
25/25 [==============================] - 30s 875ms/step - loss: 0.2282 - acc: 0.9187
Epoch 2/10
25/25 [==============================] - 21s 824ms/step - loss: 0.0752 - acc: 0.9725
Epoch 3/10
25/25 [==============================] - 21s 828ms/step - loss: 0.0512 - acc: 0.9837
Epoch 4/10
25/25 [==============================] - 20s 804ms/step - loss: 0.0370 - acc: 0.9937
Epoch 5/10
25/25 [==============================] - 21s 833ms/step - loss: 0.0290 - acc: 0.9975
Epoch 6/10
25/25 [==============================] - 20s 805ms/step - loss: 0.0227 - acc: 0.9975
Epoch 7/10
25/25 [==============================] - 20s 805ms/step - loss: 0.0180 - acc: 1.0000
Epoch 8/10
25/25 [==============================] - 21s 831ms/step - loss: 0.0151 - acc: 1.0000
Epoch 9/10
25/25 [==============================] - 20s 798ms/step - loss: 0.0128 - acc: 1.0000
Epoch 10/10
25/25 [==============================] - 20s 797ms/step - loss: 0.0113 - acc: 1.0000


10 epoch yerine 7-8 epoch yeterliymiş

In [21]:
score, acc = model.evaluate(X_test_scaled, y_test)
print("Test loss: ", score)
print("Test accuraacy:", acc)

7/7 [==============================] - 7s 714ms/step - loss: 0.0826 - acc: 0.9800
Test loss:  0.08263537287712097
Test accuraacy: 0.9800000190734863
